version: "2"
services:

  db:
    image: mysql:5.7
    container_name: "IS219_Final"
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro